add new tables about spacecraft
KAOrlov/DB_UNIVERSE pull request #10
Opened 2023-11-15 08:01 UTC by KAOrlov

2023-11-17 11:26 UTC, ScareCrowZV requested changes

2023-11-17 11:26 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_spacecraft.sql
> +CREATE TABLE DB_UNIVERSE.void.tb_spacecraft
Это не таблица летательных аппаратов, а таблица экспедиций и мы решили её переделать

2023-11-17 11:26 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_spacecraft_options.sql
> +    create_date DATETIME2 NOT NULL, -- время созданя строки
Для типа DATETIME2 указывай точность. например DATETIME2(0) - таким образом ты говоришь, что тебе важна точность до секунд, а не до миллисекунд. По умолчанию без указания MSSQL создаёт DATETIME2(3)

2023-11-17 11:26 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_spacecraft_options.sql
> +CREATE TABLE DB_UNIVERSE.void.tb_spacecraft_options
Предлагаю переименовать в tb_spacecrafts

2023-11-17 11:26 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_spacecraft_options.sql
> +    FOREIGN KEY (name_id) REFERENCES DB_UNIVERSE.void.tb_spacecraft(name_id)
У тебя же эта таблица является справочником, а не таблица экспедиций? Ссылка должна быть с другой таблицы на эту. Обычно справочник сам редко на кого-то ссылается

2023-12-06 16:56 UTC, Evalti approved these changes

2023-12-08 21:58 UTC, ScareCrowZV requested changes

2023-12-08 21:58 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_galaxies.sql
> +        ), -- как движутся солнечные массы в нутри вселеной.
внутри галактики ?

2023-12-11 13:54 UTC, ScareCrowZV approved these changes

2023-12-11 13:58 UTC, merged