create file with schema project
KAOrlov/DB_UNIVERSE pull request #11
Opened 2023-11-18 22:09 UTC by KAOrlov

2023-11-18 22:11 UTC, KAOrlov commented
Подал схему в коротком виде.

2023-11-19 17:35 UTC, ScareCrowZV requested changes
Где файл со схемой в DBML ?

2023-11-19 17:36 UTC, ScareCrowZV requested changes

2023-11-19 17:36 UTC, ScareCrowZV commented on Sсhema/sсhema_DB_UNEVERYS.sql
> +  `name_id` varchar PRIMARY KEY,
Для чего используешь апострофы? Можно писать без них.

2023-11-19 17:36 UTC, ScareCrowZV commented on Sсhema/sсhema_DB_UNEVERYS.sql
> +  `created_at` timestamp,
Тип данных DATETIME2

2023-11-19 17:36 UTC, ScareCrowZV commented on Sсhema/sсhema_DB_UNEVERYS.sql
> +  `start_flight_time` DATETIME2,
Указывай размерность типа данных

2023-11-19 17:36 UTC, ScareCrowZV commented on Sсhema/sсhema_DB_UNEVERYS.sql
> +  `employee_expedition_id` varchar,
Указывай размерность типа данных

2023-11-20 08:19 UTC, ScareCrowZV requested changes
Папка должна называться DBML

2023-11-30 15:12 UTC, ScareCrowZV requested changes
* пока убираем таблицу tb_spacecraft_options
* Добавить Null / not null
* Характеристики пока убираем
* убираем столбцы name / descriptions из tb_expedition_options и переименовываем таблицу, для отражения связи между экспедицией и планетой

2023-12-05 18:48 UTC, ScareCrowZV requested changes
Костя, через .gitignore убери папку .idea

2023-12-06 12:06 UTC, ScareCrowZV requested changes
* Нужно star_system_id переименовать в planet_id
* Добавить galaxy_id в tb_star

2023-12-06 16:59 UTC, Evalti commented on DBML/shema_DB_UNEVERYS.dbml
> +  "galaxy_id" INT [NOT NULL]
Здесь должна быть связь сущностей "планета" - "звезда" (planet_id - star_id)

2023-12-06 17:00 UTC, Evalti commented on DBML/shema_DB_UNEVERYS.dbml
> +  "planet_id" INT [NOT NULL, UNIQUE]
planet_id - этой связи здесь не должно быть

2023-12-06 17:05 UTC, Evalti requested changes
Ref:"tb_planet_system"."id" < "tb_stars"."stars_system_id"

Ref:"tb_planet_system"."id" < "tb_planet"."stars_system_id"
Вроде договорились же убрать stars_system

2023-12-07 20:23 UTC, ScareCrowZV requested changes

2023-12-07 20:23 UTC, ScareCrowZV commented on DBML/shema_DB_UNEVERYS.dbml
> +  "stars_id" VARCHAR(255)
назвать в единственном числе

2023-12-07 20:23 UTC, ScareCrowZV commented on DBML/shema_DB_UNEVERYS.dbml
> +Table "tb_planet_system" {
Планетарная система обязательно связана с галактикой

2023-12-07 20:23 UTC, ScareCrowZV commented on DBML/shema_DB_UNEVERYS.dbml
> +  "stars_id" INT [PRIMARY KEY]
В единственном числе

2023-12-08 21:55 UTC, ScareCrowZV approved these changes

2023-12-08 22:06 UTC, merged