Evstratova 1.3
KAOrlov/DB_UNIVERSE pull request #14
Opened 2023-11-19 18:06 UTC by Evalti

2023-11-19 19:06 UTC, ScareCrowZV requested changes
Посмотри мои комментарии к этому реквесту пожалуйста, они актуальны и к текущему

https://github.com/KAOrlov/DB_UNIVERSE/pull/12/files

2023-11-19 19:06 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_cat_properties.sql
> +CREATE TABLE tb_cat_properties (
Схема не указана. Вроде Костя придумал void

2023-11-19 19:06 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_cat_properties.sql
> +    name_properties VARCHAR(50) NOT NULL,
В название столбца не нужно дописывать название сущности

2023-11-20 15:30 UTC, Evalti commented on Tabels(DataDefinitionLanguage)/tb_cat_properties.sql
> +CREATE TABLE tb_cat_properties (
Добавила схему

2023-11-20 15:30 UTC, Evalti commented on Tabels(DataDefinitionLanguage)/tb_cat_properties.sql
> +    name_properties VARCHAR(50) NOT NULL,
убрала название сущности

2023-11-20 15:34 UTC, Evalti commented
> Посмотрите мои комментарии к этому ревесту, пожалуйста, они актуальны и к настоящему
> 
> https://github.com/KAOrlov/DB_UNIVERSE/pull/12/files

По этому поводу почитала о каскадном удаление и добавление таблиц, убрала по всем таблицам.

2023-12-05 20:00 UTC, KAOrlov approved these changes

2023-12-07 19:16 UTC, KAOrlov approved these changes

2023-12-07 19:47 UTC, ScareCrowZV requested changes

2023-12-07 19:47 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_planet_galaxy.sql
> +    id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
С какой целью необходимо давать идентификатор связкам?

2023-12-07 19:47 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_planet_system.sql
> +
Планетные системы всегда связаны с галактикой

2023-12-07 19:47 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_planet_galaxy.sql
> +CREATE TABLE DB_UNIVERSE.void.tb_stars_galaxy (
Ошибка в названии таблицы, файл про планеты, таблица про звёзды

2023-12-07 19:47 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_planet_galaxy.sql
> +CREATE TABLE DB_UNIVERSE.void.tb_stars_galaxy (
Отдельная таблица для связки планет не потребуется, доставточно добавить связку в таблицу tb_planets, т.к. планета да летает в какой-то галактике

2023-12-10 09:32 UTC, ScareCrowZV requested changes

2023-12-10 09:32 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_planet_system.sql
> +CREATE TABLE DB_UNIVERSE.void.tb_planet_system (
Не задан ключ для таблицы

2023-12-10 09:32 UTC, ScareCrowZV commented on Tabels(DataDefinitionLanguage)/tb_stars_galaxy.sql
> +CREATE TABLE DB_UNIVERSE.void.tb_stars_galaxy (
Не задан ключ для таблицы

2023-12-11 15:37 UTC, ScareCrowZV approved these changes

2023-12-11 17:47 UTC, merged